import { cp, mkdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
const root = new URL('.', import.meta.url);
const dist = new URL('./dist/', root);
if (existsSync(dist)) await rm(dist, { recursive:true, force:true });
await mkdir(dist, { recursive:true });
await cp(new URL('./index.html', root), new URL('./dist/index.html', root));
await cp(new URL('./src', root), new URL('./dist/src', root), { recursive:true });
await cp(new URL('./public', root), dist, { recursive:true });
console.log('EPL build ready in ./dist');
